### PR TITLE
Refactor 2pc-handshake to typestates

### PR DESCRIPTION
**Pull request by sinui0**
This PR refactors our 2pc handshake implementation to use the typestate pattern and renames from Master/Slave to Leader/Follower.

Business logic remains untouched, as can be seen by the minimal changes to the `test_prf()` unit test.

### CODE REVIEW

**Review by th4s — APPROVED** [review]
nice, ACK

**Review by themighty1 — APPROVED** [review]
Looks good but why were the comments not preserved @sinui0 ?

**Comment by themighty1** [comment]
> @themighty1 Oh good catch, are you referring to the comments on the traits? I overlooked those. They don't quite map to the new code as we won't have traits in core for this. However, I'll add back what I can and more documentation in #78

I actually meant comments like this one https://github.com/tlsnotary/tlsn/blob/d8b9f05a92874665a81285a9a4320b37f27f15fa/tls-2pc-core/src/handshake/master.rs#L65

I realize that they don't map 1:1 to the new code but at least some comments are needed next to the functions. Specifically it should be mentioned that Ms stands for master secret and Ke for Key expansion, Cf/Sf for ... etc.

**Comment by themighty1** [comment]
Ah, i was reviewing PR one by one, I just noticed that PR78 subsumes this PR, so nvm.

**Pull request merged**
