### PR TITLE
Memory profiling

### PR DESCRIPTION
**Pull request by themighty1**
This PR adds the functionality to profile memory usage of the native prover.
The gh workflow ran successfully here https://github.com/themighty1/tlsn/actions/runs/11553800582

This PR is a copy of https://github.com/tlsnotary/tlsn/pull/602

### CODE REVIEW

**Review by heeckhau — APPROVED** [review]
Looking good!

**Comment by themighty1** [comment]
I added a Co-authored-by: line but apparently github didn't pick it up. Sorry for that.

**Comment by heeckhau** [comment]
@valo Thanks again for your great contribution 🙏

**Comment by valo** [comment]
Oh no... no attribution in the git history 😢 A friendly recommendation to avoid this, as it will drive external contributors away

**Comment by themighty1** [comment]
@valo , do you know what your Co-authored-by: line should look like (for future reference)
Im sorry that there was a chain of mishaps: you were not able to respond to my request here https://github.com/tlsnotary/tlsn/pull/602#issuecomment-2422554171 
Then I waited for a week and decided to move forward. Then I tried to find your  "Co-authored-by:" line in your previous commits, but I couldn't find it. Lesson learned. 

We actually do encourage contributors and even go out of the way to atrribute their contributions. 
Your future contributions are very welcome.

**Comment by valo** [comment]
>Im sorry that there was a chain of mishaps: you were not able to respond to my request here https://github.com/tlsnotary/tlsn/pull/602#issuecomment-2422554171

For some reason the emails for this issue were going to my spam folder :-( On the top of this, I was attending some events and not paying attention to GitHub that much. I should have paid more attention to this.

`Co-authored-by: Valentin Mihov <valentin.mihov@gmail.com>`

**Comment by themighty1** [comment]
@valo , thanks
https://github.com/tlsnotary/tlsn/pull/660
is the best we could come up with. You are attributed now, albeit in a non-straightforward manner.

**Pull request merged**
